### ISSUE TITLE
Check if the README file of the project brings "useful" information.

### ISSUE THREAD

**Issue by joseedil** [forsyde/forsyde-shallow-examples#11]
@ingo-sander had some problems using the instructions on the README and was able to runs the examples only after I showed him how to.

**Comment by ugeorge** [comment]
I need a more specific description of the problem. Is there something missing or not working?

**Comment by joseedil** [comment]
Please ask Ingo, he complained there was something missing but I can't remember now what was it.

**Comment by joseedil** [comment]
He could not make the examples work with this:

> To install the applications globaly, you can use the following commands, provided you have installed Cabal:
> cabal install    # installs 'forsyde-shallow-examples' and all its dependencies globally
> ghci             # opens a GHC interpreter session from which you can import the applications

I did the following in his machine and it worked:
> To install the applications locally in a sandbox, you can use the following commands:
> cabal sandbox init # creates a sandbox in the current folder
> in case 'ForSyDe.Shallow' is not globally installed, you need to download/clone its source repo, and type
> cabal sandbox add-source <path/to/forsyde-shallow>
> cabal install      # installs 'forsyde-shallow-examples' and all its dependencies locally, in the sandbox
> cabal repl         # opens a GHC interpreter session for the sandbox from which you can import the applications

So, it looks like the global install is somehow not working.

**Comment by ugeorge** [comment]
@ingo-sander @joseedil : did you have `ForSyDe-Shallow` installed globally? What is the error output? Please do a proper error report, since I see no reason not to work using `cabal install`.
